name: Auto Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle
          cache-dependency-path: |
            app/**/*.gradle*
            app/gradle/wrapper/gradle-wrapper.properties
            app/gradle/libs.versions.toml

      - name: Build APK
        working-directory: app
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      - name: List APK outputs
        run: ls -la app/app/build/outputs/apk/release/

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          repository: xqh0927/sheeps-releases
          token: ${{ secrets.MY_PAT }}
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          # 修正路径：如果执行是在 app 目录下，APK 就在 app/build/outputs/...
          # 也就是相对于根目录的 app/build/outputs/...
          files: app/app/build/outputs/apk/release/*.apk
          fail_on_unmatched_files: true
