name: Auto Release
on:
  push:
    branches: [ "main" ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract version
        id: get_version
        run: |
          # 提取 versionName 并清理所有引号和空格
          VERSION=$(grep "versionName" app/build.gradle.kts | sed 's/.*"\(.*\)".*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Build APK
        run: |
          cd app
          chmod +x gradlew
          ./gradlew assembleRelease
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repository: xqh0927/sheeps-releases
          token: ${{ secrets.MY_PAT }}
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: app/build/outputs/apk/release/sheeps_*.apk